dist: bionic
sudo: required
env:
  matrix:
    - PYVER=python36_ubuntu_1804 SKIP_SHELLCHECK=1 SKIP_MYPY=1 SKIP_VULTURE=1
    - PYVER=current_arch SKIP_SHELLCHECK=0 SKIP_MYPY=0 SKIP_VULTURE=0
services:
  - docker
git:
  submodules: false
install:
  - mv ./dockerfiles/* ./
  - travis_retry docker build . -f Dockerfile_${PYVER} -t oomox
script:
  - docker run
      -e SKIP_SHELLCHECK=${SKIP_SHELLCHECK}
      -e SKIP_MYPY=${SKIP_MYPY}
      -e SKIP_VULTURE=${SKIP_VULTURE}
      oomox:latest
      ./maintenance_scripts/run_ci.sh
